/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.List;

public class AppTest {

    App logic = new App();

    @Test
    public void testAdd() {
        assertEquals(5, logic.add(2, 3));
        assertEquals(-1, logic.add(2, -3));
    }

    @Test
    public void testIsPalindrome() {
        assertTrue(logic.isPalindrome("madam"));
        assertFalse(logic.isPalindrome("hello"));
    }

    @Test
    public void testGetMaxNumber() {
        List<Integer> numbers = Arrays.asList(1, 5, 3, 9, 2);
        assertEquals(9, logic.getMaxNumber(numbers));
    }

    @Test
    public void testConvertCelsiusToFahrenheit() {
        assertEquals(32.0, logic.convertCelsiusToFahrenheit(0));
        assertEquals(104.0, logic.convertCelsiusToFahrenheit(40));
    }

    @Test
    public void testFactorial() {
        assertEquals(120, logic.factorial(5));
        assertEquals(1, logic.factorial(0));
    }
}

